# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: JS client CI

on:
  push:
    branches: [ master ]
    paths:
      - client-js/**
      - .github/workflows/client-js.yml
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      server:
        image: asanrom/parallel-request-controller
        env:
          AUTH_TOKEN: 'secret'
        ports:
          - 8080:8080
    steps:
    - uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./client-js
      run: npm install

    - name: Build source code
      working-directory: ./client-js
      run: npm run build

    - name: Run tests
      working-directory: ./client-js
      run: npm test
      env:
        AUTH_TOKEN: 'secret'
