name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set env RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 . --file Dockerfile --tag ghcr.io/agustinsrg/parallel-request-controller:latest --tag asanrom/parallel-request-controller:latest --tag ghcr.io/agustinsrg/parallel-request-controller:${{ env.RELEASE_VERSION }} --tag asanrom/parallel-request-controller:${{ env.RELEASE_VERSION }}

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: asanrom
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Push the Docker image (Current Version)
      run: docker push asanrom/parallel-request-controller:${{ env.RELEASE_VERSION }}
        
    - name: Push the Docker image (Latest)
      run: docker push asanrom/parallel-request-controller:latest

    - name: Docker Login (GitHub Packages)
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image (GitHub Packages) (Current Version)
      run: docker push ghcr.io/agustinsrg/parallel-request-controller:${{ env.RELEASE_VERSION }}
        
    - name: Push the Docker image (GitHub Packages) (Latest)
      run: docker push ghcr.io/agustinsrg/parallel-request-controller:latest
    
