# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Server CI

on:
  push:
    branches: [ "master" ]
    paths:
      - server/**
      - .github/workflows/server.yml
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.x

    - name: Build and test server
      working-directory: ./server
      run: go build . && go test -v
